// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ9yZx56gBWMsOYiBoQVHFu9ltivN_dg4',
    appId: '1:335661246703:web:eb74dd6624a146a8e7931a',
    messagingSenderId: '335661246703',
    projectId: 'license-gen-db',
    authDomain: 'license-gen-db.firebaseapp.com',
    storageBucket: 'license-gen-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHT9oKXKyzwH_W-4kyD6SpcRx6g8vu9Vw',
    appId: '1:335661246703:android:ade28bc25ed5d959e7931a',
    messagingSenderId: '335661246703',
    projectId: 'license-gen-db',
    storageBucket: 'license-gen-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJvWam3x2I2Erou8wLv5y7htTHWEmRpGg',
    appId: '1:335661246703:ios:b3c212bfa4b2912ae7931a',
    messagingSenderId: '335661246703',
    projectId: 'license-gen-db',
    storageBucket: 'license-gen-db.firebasestorage.app',
    iosBundleId: 'com.example.buyVerifyLicense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJvWam3x2I2Erou8wLv5y7htTHWEmRpGg',
    appId: '1:335661246703:ios:b3c212bfa4b2912ae7931a',
    messagingSenderId: '335661246703',
    projectId: 'license-gen-db',
    storageBucket: 'license-gen-db.firebasestorage.app',
    iosBundleId: 'com.example.buyVerifyLicense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ9yZx56gBWMsOYiBoQVHFu9ltivN_dg4',
    appId: '1:335661246703:web:0f00af7d1ccba3f9e7931a',
    messagingSenderId: '335661246703',
    projectId: 'license-gen-db',
    authDomain: 'license-gen-db.firebaseapp.com',
    storageBucket: 'license-gen-db.firebasestorage.app',
  );
}
